
GET http://localhost:3000/api/v1/projects

###
POST http://localhost:3000/api/v1/projects
Content-Type: application/json

{
    "title": "Test Title 3",
    "description": "Test description",
    "url": "http://localhost:3000/api/v1",
    "client": "Test Client",
    "urlClient": "Test Url"
}

###
PUT http://localhost:3000/api/v1/projects

###
DELETE http://localhost:3000/api/v1/projects


###

GET http://localhost:3000/api/v1/token